### ISSUE TITLE
Func Call Problem

### ISSUE THREAD

**Issue by sekiguchi-nagisa** [libbun/libbun#16]
can not work following script

$ cat ./call.bun
function f() : String {
    return "hello";
}

export function main() {
    f();
}
$ java -jar libbun-0.1.jar -t jvm call.bun
(call.bun:6) [error] not function
    f();
     ^
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at libbun.encode.jvm.AsmJavaGenerator.ExecMain(AsmJavaGenerator.java:1209)
    at libbun.main.Main.InvokeLibBun(Main.java:130)
    at libbun.main.Main.main(Main.java:137)
Caused by: libbun.util.SoftwareFaultException: SoftwareFault: (call.bun:6) [error] not function
    f();
     ^
    at libbun.encode.jvm.JavaOperatorApi.ThrowError(JavaOperatorApi.java:267)
    at F__main__0qqw.f(call.bun:6)
    ... 7 more

**Comment by sekiguchi-nagisa** [comment]
fix at commit 47d0d3b329529effd0b3f51d5866f23fc9c16124
